apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "128Mi"

  securityContext:
    runAsNonRootUser: true
    runAsUser: 1000
    spec:
      containers:
      - name: redis
        image: redis:7.2
        ports:
        - containerPort: 6379
