- name: Configure EC2
  hosts: ec2
  become: yes

   tasks:
    - name: update apt packages
      apt:
        update_cache: yes
    
     - name: Install Docker
      apt:
        name: docker.io
        state: present
    
    - name: install git 
      apt:
        name: git 
        state: present
    
    - name: clone my github repo
      git:
        repo: "https://github.com/Kevin8941743/todo-list-api"
        dest: /home/ubuntu/roadmap-api
    
    - name: Install dependencies
      command: npm install
      args:
        chdir: /home/ubuntu/roadmap-api