- name: Configure EC2
  hosts: ec2
  become: yes

  tasks:
    - name: update apt packages
      apt:
        update_cache: yes
    
    - name: Install Docker
      apt:
        name: docker.io
        state: present
    
    - name: Install docker compose
      apt: 
        name: docker-compose
        state: present
    
    - name: Start the docker servie 
      service:
        name: docker
        state: started
        enabled: yes
    
    - name: install git 
      apt:
        name: git 
        state: present
    
    - name: clone my github repo
      git:
        repo: "https://github.com/Kevin8941743/todo-list-api.git"
        dest: /home/ubuntu/todo-api
        update: yes
    
    - name: Copy env file
      copy:
        src: /Users/Kevinthapa/todo-api/app/.env
        dest: /home/ubuntu/todo-api/app/.env
    
    - name: Stop any docker-compose containers 
      command: docker-compose down
      args:
        chdir: /home/ubuntu/todo-api/app

    - name: Start docker compose 
      command: docker-compose up -d --build
      args:
        chdir: /home/ubuntu/todo-api/app