- name: Configure EC2
  hosts: ec2
  become: yes

   tasks:
    - name: update apt packages
      apt:
        update_cache: yes
    
     - name: Install Docker
      apt:
        name: docker.io
        state: present
    
    - name: install git 
      apt:
        name: git 
        state: present